server:
  port: ${PORT:8102}

spring:
  application:
    name: vg-ms-students
  data:
    mongodb:
      uri: mongodb+srv://vallegrandeomar:oFnm1G368PeimZNj@cluster0.srr0s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: vg_ms_students

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    pe.edu.vallegrande: DEBUG
    org.springframework.web: DEBUG
    com.mongodb: DEBUG 